//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.12 at 09:32:50 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "generating_people", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package generating_people;
